# Generated by Django 4.2.5 on 2023-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoints', '0002_remove_appointment_user_appointment_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
